micronaut:
  application:
    name: cleanURI-apigateway
  server:
    port: -1 # Disable server port for testing
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /oas3/**
netty:
  default:
    allocator:
      max-order: 3


# https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/#config
rabbitmq:
  enabled: false

gateway:
  cache-timeout: 30s
  cache-evict: 300s
  amqp-result-queue: amqp-result
  amqp-task-queue: amqp-task
