micronaut:
  application:
    name: cleanURI-apigateway
  server:
    port: ${PORT:8080}
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /oas3/**

netty:
  default:
    allocator:
      max-order: 3

endpoints:
  health:
    enabled: true

# https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/#config
rabbitmq:
  host: ${AMQP_HOST}
  username: ${AMQP_USER:}
  password: ${AMQP_PASS}
  virtual-host: ${AMQP_VHOST:/}

gateway:
  cache-timeout: ${GATEWAY_CACHE_TIMEOUT:30s}
  cache-evict: ${GATEWAY_CACHE_EVICT:300s}
  amqp-result-queue: ${GATEWAY_RESULT_QUEUE}
  amqp-task-rk: ${GATEWAY_TASK_RK}
